before:
  hooks:
    - go mod download
builds:
- main: ./cmd/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - linux
  - darwin 
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
      - LICENSE
      - README.md
      - plugin/*.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: instrumenta
    name: homebrew-instrumenta
  folder: Formula
  description: "Test your configuration using Open Policy Agent"
  homepage: "https://github.com/instrumenta/conftest"
  test: |
    system "#{bin}/conftest --version"
scoop:
  bucket:
    owner: instrumenta
    name: scoop-instrumenta
  description: "Test your configuration using Open Policy Agent"
  homepage: "https://github.com/instrumenta/conftest"
