version: 2.1
commands:
  install_snyk:
    description: "Install Snyk"
    steps:
      - run:
          name: Install Snyk
          command: |
            if [[ ! -x "/usr/local/bin/snyk" ]]; then
              curl -s https://api.github.com/repos/snyk/snyk/releases/latest | grep "browser_download_url" | grep linux | cut -d '"' -f 4 | wget -qi -
              sha256sum -c snyk-linux.sha256
              sudo mv snyk-linux /usr/local/bin/snyk
              sudo chmod +x /usr/local/bin/snyk
            fi

jobs:
  build:
    docker:
      - image: circleci/golang:1.12-node

    steps: 
      - checkout 
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run: go test ./... 
      - run:
          name: Build binary
          command: go build -o conftest
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Install Bats
          command: | 
            cd /tmp
            curl -L https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz | tar -xz
            sudo ./bats-0.4.0/install.sh /usr/local
      - install_snyk
      - run:
          name: Run acceptance tests
          command: |
            sudo npm install tap-xunit -g
            mkdir -p ~/reports
            bats acceptance.bats --tap | tap-xunit > ~/reports/conftest.xml
      - run:
          name: Run security tests on Go dependencies 
          command: snyk monitor
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
  image:
    docker:
      - image: circleci/buildpack-deps:stretch 

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - install_snyk
      - run:
          name: Build image
          command: docker build -t instrumenta/conftest .
          environment:
            DOCKER_BUILDKIT: 1
      - run:
          name: Run security tests on Docker image
          command: snyk monitor --docker instrumenta/conftest --file=Dockerfile --project-name=docker.io/instrumenta/conftest

workflows:
  version: 2
  build:
    jobs:
      - build
      - image

