version: 2.1
commands:
  install_snyk:
    description: "Install Snyk"
    steps:
      - run:
          name: Install Snyk
          command: |
            if [[ ! -x "/usr/local/bin/snyk" ]]; then
              curl -s https://api.github.com/repos/snyk/snyk/releases/latest | grep "browser_download_url" | grep linux | cut -d '"' -f 4 | wget -qi -
              sha256sum -c snyk-linux.sha256
              sudo mv snyk-linux /usr/local/bin/snyk
              sudo chmod +x /usr/local/bin/snyk
            fi
  check_code_with_snyk:
    description: "Monitor dependencies with Snyk"
    parameters:
      project:
        type: string
        default: ""
      args:
        type: string
        default: ""
      type:
        type: enum
        default: "monitor"
        enum: ["monitor", "test"]
    steps:
      - run:
          name: Run Snyk to check dependencies 
          command: snyk << parameters.type >> --file=<< parameters.project >> << parameters.args >>
  check_docker_with_snyk:
    description: "Monitor Docker images with Snyk"
    parameters:
      image:
        type: string
      dockerfile:
        type: string
        default: Dockerfile
      tag:
        type: string
        default: latest
      project:
        type: string
        default: ""
      args:
        type: string
        default: ""
      type:
        type: enum
        default: "monitor"
        enum: ["monitor", "test"]
    steps:
      - run:
          name: Run Snyk to check dependencies 
          command: snyk << parameters.type >> --docker << parameters.image >>:<< parameters.tag >> --file=<< parameters.dockerfile >> --project-name=<< parameters.project >> << parameters.args >>


jobs:
  build:
    docker:
      - image: circleci/golang:1.12-node

    steps: 
      - checkout 
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run: go test ./... 
      - run:
          name: Build binary
          command: go build -o conftest
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Install Bats
          command: | 
            cd /tmp
            curl -L https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz | tar -xz
            sudo ./bats-0.4.0/install.sh /usr/local
      - install_snyk
      - run:
          name: Run acceptance tests
          command: |
            sudo npm install tap-xunit -g
            mkdir -p ~/reports
            bats acceptance.bats --tap | tap-xunit > ~/reports/conftest.xml
      - check_code_with_snyk
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
  image:
    docker:
      - image: circleci/buildpack-deps:stretch 

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - install_snyk
      - run:
          name: Build image
          command: docker build -t instrumenta/conftest .
          environment:
            DOCKER_BUILDKIT: 1
      - check_docker_with_snyk:
          image: instrumenta/conftest
          project: docker.io/instrumenta/conftest

workflows:
  version: 2
  build:
    jobs:
      - build
      - image

